version: '3.7'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
  app:
    build:
      context: .
      dockerfile: backend.dockerfile
    command: python3 hello.py
    environment:
      # print python console output while running docker
      PYTHONUNBUFFERED: 1
      DYNAMODB_ADDRESS: "dynamodb-local:8000"
    depends_on:
      - dynamodb-local

